#!/bin/bash
################################################################################
##   ____  ____
##  /   /\/   /
## /___/  \  /    Vendor: Xilinx
## \   \   \/     Version : 1.04
##  \   \         Application : ILA v1.04_a Core
##  /   /         Filename : implement_sh.ejava 
## /___/   /\     
## \   \  /  \
##  \___\/\___\
##
##
## implement.sh script 
## Generated by Xilinx ILA v1.04_a Core
##
#-----------------------------------------------------------------------------
# Script to synthesize and implement the RTL provided for the ILA core
#-----------------------------------------------------------------------------
#Exit on Error enabled.
set -o errexit

#Create results directory
rm -rf results
mkdir results

echo 'Running Coregen on ICON required for example design'
coregen -b chipscope_icon.xco -p coregen.cgp
# Check Results
if [ $? -gt 0 ] ; then 
echo An error occurred running Coregen on ICON
echo FAIL
exit
fi

cp ../../coregen_ila.ngc .

##-------------------------------Run Xst on Example design----------------------------
echo 'Running Xst on example design'
xst -ifn example_coregen_ila.xst -ofn example_core.log -intstyle silent
# Check Results
if [ $? -gt 0 ] ; then 
echo An error occurred running XST on example_coregen_ila
echo FAIL
exit
fi

cp chipscope_icon.ngc ./results

cp ../../coregen_ila.ngc        ./results
cp example_coregen_ila.ngc        ./results
cd ./results
##-------------------------------Run ngdbuild---------------------------------------
echo 'Running ngdbuild'
ngdbuild -uc ../../example_design/example_coregen_ila.ucf -p xc6slx9-csg324-3 -sd . example_coregen_ila.ngc example_coregen_ila.ngd
if [ $? -gt 0 ] ; then 
echo An error occurred running NGDBUILD on example_coregen_ila 
echo FAIL
exit
fi
#end run ngdbuild section
##-------------------------------Run map-------------------------------------------
echo 'Running map'
map -w -p xc6slx9-csg324-3 -o example_coregen_ila.map.ncd example_coregen_ila.ngd
if [ $? -gt 0 ] ; then 
echo An error occurred running MAP on example_coregen_ila 
echo FAIL
exit
fi
##-------------------------------Run par-------------------------------------------
echo 'Running par'
par -w -ol high example_coregen_ila.map.ncd example_coregen_ila.ncd 
if [ $? -gt 0 ] ; then 
echo An error occurred running PAR on example_coregen_ila 
echo FAIL
exit
fi
##---------------------------Report par results-------------------------------------
echo 'Running design through bitgen'
bitgen -d -g GWE_cycle:Done -g GTS_cycle:Done -g DriveDone:Yes -g StartupClk:Cclk -w example_coregen_ila.ncd
if [ $? -gt 0 ] ; then 
echo An error occurred running BITGEN on example_coregen_ila 
echo FAIL
exit
else
echo PASS
exit
fi
