################################################################################
##   ____  ____
##  /   /\/   /
## /___/  \  /    Vendor: Xilinx
## \   \   \/     Version : 1.05
##  \   \         Application : ICON v1.05_a Core
##  /   /         Filename : pa_implement.ejava
## /___/   /\     
## \   \  /  \
##  \___\/\___\
##
##
## pa_implement.tcl script 
## Generated by Xilinx ICON v1.05_a Core
##
#-----------------------------------------------------------------------------
# Script to synthesize and implement the RTL provided for the ICON core
#-----------------------------------------------------------------------------
add_files -norecurse {../example_design/example_coregen_icon.v}
add_files -norecurse {../example_design/example_coregen_icon.ucf}
import_ip -file {chipscope_vio.xco} -name chipscope_vio
set_property top example_coregen_icon [get_filesets sources_1]
reset_run -run synth_1
launch_runs synth_1
